/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['events.js']) {
  _$jscoverage['events.js'] = [];
  _$jscoverage['events.js'][1] = 0;
  _$jscoverage['events.js'][2] = 0;
  _$jscoverage['events.js'][6] = 0;
  _$jscoverage['events.js'][7] = 0;
  _$jscoverage['events.js'][9] = 0;
}
_$jscoverage['events.js'][1]++;
(function () {
  _$jscoverage['events.js'][2]++;
  var events = {news: "news", test: "test"};
  _$jscoverage['events.js'][6]++;
  if (module) {
    _$jscoverage['events.js'][7]++;
    module.exports = events;
  }
  _$jscoverage['events.js'][9]++;
  return events;
})();
_$jscoverage['events.js'].source = ["(function() {","    var events = {","        news: 'news',","        test: 'test'","    };","    if (module) {","            module.exports = events;","    }","    return events;","})();"];
